name: Build IPK

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build IPK
        run: |
          # 1. Siapkan struktur direktori
          mkdir -p ipk/CONTROL
          mkdir -p ipk/usr/lib/lua/internet-detector/modules/
          
          # 2. Salin file modul
          cp internet-detector-mod-whatsapp/data/usr/lib/lua/internet-detector/modules/mod_whatsapp.lua ipk/usr/lib/lua/internet-detector/modules/
          
          # 3. Buat file control
          cat <<EOF > ipk/CONTROL/control
          Package: internet-detector-mod-whatsapp
          Version: 1.0.0
          Section: net
          Architecture: all
          Maintainer: Akang
          Description: Modul WhatsApp untuk Internet Detector
          EOF
          
          # 4. Buat paket menggunakan format ar (standar opkg)
          cd ipk
          tar -czf control.tar.gz -C CONTROL .
          tar -czf data.tar.gz --exclude=./CONTROL .
          echo "2.0" > debian-binary
          ar -r ../internet-detector-mod-whatsapp_1.0.0_all.ipk debian-binary control.tar.gz data.tar.gz
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: internet-detector-mod-whatsapp
          path: internet-detector-mod-whatsapp_1.0.0_all.ipk
